
DROP TABLE IF EXISTS PLAYER;

CREATE TABLE PLAYER(
    ID VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    JOIN_DATE DATETIME
);

DROP TABLE IF EXISTS GAME;

CREATE TABLE GAME (
    ID VARCHAR(100) NOT NUll,
    WHITE VARCHAR(100),
    BLACK VARCHAR(100),
    DATE DATETIME,
    TIME_CONTROL VARCHAR(50),
    PGN VARCHAR(200),
    RESULT VARCHAR(20),
    FOREIGN KEY(WHITE) REFERENCES PLAYER(ID)
);

DROP TABLE IF EXISTS WAIT_LIST;

CREATE TABLE WAIT_LIST(
    PLAYER VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME,
    TIME_CONTROL VARCHAR(50),
    FOREIGN KEY (PLAYER) REFERENCES PLAYER(ID)
);